plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.telegram:telegrambots-longpolling:9.5.0'
    implementation 'org.telegram:telegrambots-client:9.5.0'
    implementation 'ch.qos.logback:logback-classic:1.4.14' // For logging
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes 'Main-Class': 'org.example.Main'
    }
}

shadowJar {
    archiveBaseName.set('MiniArbuzikbot')
    archiveVersion.set('1.0-SNAPSHOT')
    archiveClassifier.set('all')
    manifest {
        inheritFrom project.tasks.jar.manifest
    }
}